# REQUIRED
variable "max_size" {
  description = "The maximum size of the auto scale group"
}
variable "min_size" {
  description = "The minimum size of the auto scale group"
}
variable "launch_configuration" {
  description = "The name of the launch configuration to use"
}
# OPTIONAL
variable "name" {
  description = "The name of the auto scale group.  By default generated by terraform."
}
variable "availability_zones" {
  description = "A list of AZs to launch resources in. Required only if you do not specify any vpc_zone_identifier"
}